# Generated by Django 4.1.4 on 2023-01-06 09:57

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.datetime


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('SP', 'Swimming Pool'), ('PG', 'Childrens Playground'), ('BP', 'BBQ Pit'), ('L', ' Music Lounge'), ('CS', 'Convenience Store'), ('MR', ' Meeting Room'), ('O', 'Others')], max_length=5)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=250)),
                ('family_name', models.CharField(max_length=250)),
                ('given_name', models.CharField(max_length=250)),
                ('preferred_name', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(error_messages={'unique': 'Thie email has already ben registered'}, max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(max_length=250)),
                ('given_name', models.CharField(max_length=250)),
                ('preferred_name', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(error_messages={'unique': 'Thie email has already ben registered'}, max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('type', models.CharField(choices=[('L', 'Leasehold'), ('F', 'Freehold'), ('O', 'Others')], max_length=1)),
                ('address', models.CharField(max_length=250)),
                ('postal_code', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=10)),
                ('web', models.URLField()),
                ('email', models.EmailField(error_messages={'unique': 'Thie email has already ben registered'}, max_length=254, unique=True)),
                ('contract_period', models.CharField(choices=[('1', '1 Year'), ('3', '3 Years'), ('5', '5 Years')], max_length=1)),
                ('start_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.manager')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(blank=True, max_length=50, null=True)),
                ('floor', models.CharField(blank=True, max_length=50, null=True)),
                ('unit_number', models.CharField(max_length=10)),
                ('share_value', models.PositiveIntegerField(blank=True, default=100, null=True)),
                ('ownership_start_date', models.DateField()),
                ('maintenance_fee_monthly', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sinking_fund_monthly', models.DecimalField(decimal_places=2, max_digits=10)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.owner')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.property')),
            ],
        ),
        migrations.AddConstraint(
            model_name='owner',
            constraint=models.UniqueConstraint(fields=('given_name', 'family_name'), name='unique_owner'),
        ),
        migrations.AddConstraint(
            model_name='manager',
            constraint=models.UniqueConstraint(fields=('given_name', 'family_name'), name='unique_manager'),
        ),
        migrations.AddField(
            model_name='facility',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.property'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.CheckConstraint(check=models.Q(('ownership_start_date__lte', django.db.models.functions.datetime.Now())), name='ownership_start_date must be less than or equal today'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(check=models.Q(('start_date__lte', django.db.models.functions.datetime.Now())), name='start_date must be less than or equal today'),
        ),
        migrations.AddConstraint(
            model_name='facility',
            constraint=models.UniqueConstraint(fields=('property', 'name'), name='unique_facility'),
        ),
    ]
