# Generated by Django 4.1.4 on 2023-01-03 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0002_remove_manager_start_date_property_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='unit_number',
            field=models.CharField(max_length=10),
        ),
    ]
